### ISSUE TITLE
[FATAL] stream error: stream ID 9; INTERNAL_ERROR; received from peer

### ISSUE THREAD

**Issue by jefflou** [bookstairs/bookhunter#22]
* **Version**:
* **Platform**:

下载教材遇到错误，[FATAL] stream error: stream ID 9; INTERNAL_ERROR; received from peer。请问如何解决？可否根据教材文件名单独下载？

**Comment by syhily** [comment]
This could occurred only when you are using the tools behind the proxy or a weak network connection. Can you check it?

**Comment by syhily** [comment]
The name filter is WIP by a contributor, we may get it merged soon to support your request.
https://github.com/bookstairs/bookhunter/pull/23
