### ISSUE TITLE
不支持windows 7？

### ISSUE THREAD

**Issue by admin05** [bookstairs/bookhunter#24]
* **Version**:0.14.0
* **Platform**:64-bit Windows 7

运行后出现如下错误提示：
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fc70 sp=0x22fc50 pc=0x471235
rax     0x0
rbx     0x1e3f080
rcx     0x1e95180
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdb0
rsp     0x22fc48
r8      0x0
r9      0x22feb8
r10     0x1
r11     0x0
r12     0x22fea0
r13     0x20
r14     0x1e3ea20
r15     0xfe80
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

**Comment by syhily** [comment]
The support for Windows 7 has been dropped since Golang 1.21. You can clone this project and build the binary by yourself on Golang 1.19.

https://github.com/golang/go/issues/57003

**Comment by syhily** [comment]
The last release you can use on Windows 7 is here: https://github.com/bookstairs/bookhunter/releases/tag/v0.11.3

Feel free to reopen this issue if you have any questions.
