### ISSUE TITLE
version subcommand can not show program version

### ISSUE THREAD

**Issue by hellojukay** [bookstairs/bookhunter#7]
![image](https://user-images.githubusercontent.com/10371891/164181169-abaabee5-c943-4b38-b987-1e1c65620d53.png)
# How did i install bookhunter?
```
go install  github.com/bibliolater/bookhunter@latest
```
# What is my computer platform?
```
Windows 10 
```
# Which version of your golang compile?
```
go version go1.18 windows/amd64
```

**Comment by syhily** [comment]
This version should be provided at building time. As for windows user, you can use [scoop](https://scoop.sh/) to install the precompile bookhunter: https://github.com/bibliolater/scoop-bucket.

**Comment by hellojukay** [comment]
@syhily ok , i got it.
